### ISSUE TITLE
Take a look at feathers-orm-service which uses sequelize

### ISSUE THREAD

**Issue by Glavin001** [feathersjs/feathers-sequelize#1]
See https://github.com/Glavin001/feathers-orm-service

Very old repository, but maybe be of interest.

**Comment by ekryski** [comment]
Sweet thanks @Glavin001.

**Comment by daffl** [comment]
Thanks! v0.1.0 actually looks quite similar except that it is using their Promise API and run against our unified DB adapter tests.
