### ISSUE TITLE
N:N relation using React Native

### ISSUE THREAD

**Issue by devfelipereis** [feathersjs/feathers-sequelize#109]
Sorry for posting here but I'm really not undertanding how can I make a request(I'm using socket) and get data from a N:N relationship.

I'm using MySQL.

Thank you!

**Comment by DesignByOnyx** [comment]
See if this helps: http://stackoverflow.com/a/42846215/264794

If not, can you please join [Slack](http://slack.feathersjs.com/) and ask in the "sequelize-qa" room.

**Comment by eddyystop** [comment]
@DesignByOnyx Do you think we should link to this in the docs until something else is put together?
