### ISSUE TITLE
Model.create ignoring field and virtual setters

### ISSUE THREAD

**Issue by buske** [feathersjs/feathers-sequelize#113]
Model setters are now being ignored on Model create. This error was introduced in commit c3751111bc278a1524711c795bd446e5e698c14e as part of the feathers-sequelize 2.0 upgrade. In particular, this line: https://github.com/feathersjs/feathers-sequelize/commit/c3751111bc278a1524711c795bd446e5e698c14e#diff-1fdf421c05c1140f6d71444ea2b27638R115

Unlike most sequelize methods such as `findAll` where the `raw` option causes sequelize to return raw JSON data, this option bizarrely means something completely different for `Model.create` (see [sequelize docs](http://docs.sequelizejs.com/en/latest/api/model/#createvalues-options-promiseinstance)):
> options.raw: If set to true, values will ignore field and virtual setters.

**Comment by wedneyyuri** [comment]
Maybe it's also affecting the `update` method. After a fresh installation the `PUT` method is not working.

Steps:

- Start a new project
- Setup sequelize
- Create the user service
- ![image](https://cloud.githubusercontent.com/assets/7511692/26164778/13a10e92-3b04-11e7-80fb-c2088fd44def.png)
- Create a new user
- Update the user
- Fetch the user from database

Full example project: https://github.com/wedneyyuri/feathers-sequelize-crud-example

**Comment by daffl** [comment]
Closed via #114
