### ISSUE TITLE
many to many (through model, with extra field in junction table) error "<Model1> is not associated to <Model2>"

### ISSUE THREAD

**Issue by kk4fun** [feathersjs/feathers-sequelize#126]
Hi. I'm new in feathersj , sequelize and web. So i'm trying to create simple first app and  i need some backend for it.
Now about the current problem:
I have 3 sequelize models - receipts,ingredients and receiptsIngredients
You can see all code here (hooks, models, associations etc.)
https://github.com/kk4fun/feathers-server-receiptsmania

So , when i send get request in postman i get an error:
```
{
    "name": "GeneralError",
    "message": "ingredients is not associated to receipts!",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```
And there's one note: in _postgres.js_ file here, where associations are set i don't see this log. But it auto-generated feathers code. May be it helps.
```
 Object.keys(models).forEach(name => {
      if ('associate' in models[name]) {
        console.log('!!!');
        models[name].associate(models);
      }
    });
```
And i don't understand now what is wrong and why i can't see receipts with ingredients throw receipts service with sequelize include before hook. Help me, please :)

=======================================
I'm doing it on Windows 10 x64, in VS code editor.

**Comment by eddyystop** [comment]
Since you are new to web development, wouldn't it be a better learning experience to start with the straightforward NeDB DB rather than with the complexity of Sequelize?

**Comment by eddyystop** [comment]
Nedb uses flat files on your local system. It does not require a service to connect to. It's stupid simple to serve up.  It does everything that feathers supports that's dB independent.

Yes your problem invloves associations which even experienced people can have issues with.

**Comment by kk4fun** [comment]
@eddyystop Thx for explanations about Nedb!

> Yes your problem invloves associations which even experienced people can have issues with.

Yes, i understand it but may be you know how to fix this in my case?

Or may be , if it's associations trouble would i create issue here https://github.com/sequelize/sequelize/issues ?

**Comment by eddyystop** [comment]
I'm not familiar with sequelae.  I would think the problem is with your syntax not with sequelize. Perhaps you can ask Ryan-wheel on slack.

This is the kind of situation you don't really want while learnin and why I recommended nedb.

**Comment by kk4fun** [comment]
> This is the kind of situation you don't really want while learnin and why I recommended nedb.

Yes, i agree. Thanks a lot.
