### ISSUE TITLE
Hook Includes not working

### ISSUE THREAD

**Issue by lfernando-silva** [feathersjs/feathers-sequelize#134]
I'm having some problems with Sequelize associations, that not working, basically the same problem of #126 , but is it needs to be using postgresql. Also, I tried [this](https://stackoverflow.com/questions/42841810/feathers-js-sequelize-service-with-relations-between-two-models) as Im using the last feathers-cli and also tried every issue at this repository.

How to make it work?

### Steps to reproduce

'Device' is a Sequelize Model generated by a feathers service. Every device has a FK to Model 'Firmware', as 1:N relationship.

Then, I'm able to make GET /devices and GET /devices/id and so on.

**device.model.js**
```js
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient')
  const devices = sequelizeClient.define('device', {
    id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      field: 'id'
    },
    firmwareId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: 'firmware',
        key: 'id'
      },
      field: 'firmware_id'
    },
//... other fields
  }, {
    classMethods: {
      associate (models) { 
        device.belongsTo(models.firmware)
      }
    }
  });
  return device;
};
```
**firmware.model.js**
```js
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient')
  const models = sequelizeClient.define('firmware', {
    id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      field: 'id'
    },
//... other fields
  }, {
    classMethods: {
      associate (models) { 
        firmware.hasMany(models.device)
      }
    }
  })
  return firmware
}
```
**device.services.js**
```js
//Before find hook, it's called properly
const onBeforeFind = hook => {
  const Firmware = hook.app.service('firmware').Model
  const Device = hook.app.service('device').Model
  hook.params = {
    sequelize: {
      model: Devices,
      include: [{
        model: Firmware,
      }]
    }
  }
  return Promise.resolve(hook)
}
```
### Expected behavior
The results should be contain informations of the related model (firmware).

### Actual behavior
The response is 
```json
{
  "name": "GeneralError",
  "message": "firmware is not associated to device!",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}
```
At debug, I realized the 'associations' property of Sequelize Model is empty and throws this error at Sequelize library.

I realized the same problem of #126 at `postgres.js`.
I even tried to switch .hasMany and .belongsTo, but the error remains (I think is not a relationship problem).

### System configuration

**Module versions** (especially the part that's not working):
"feathers-sequelize": "^2.0.1"
"sequelize": "^4.1.0"

**NodeJS version**:
v. 6.10.3 LTS

**Operating System**:
Linux Fedora Release 25

**Browser Version**:
Postman 5.0.2

**React Native Version**:
Not using

**Module Loader**:
Default

**Comment by daffl** [comment]
You are using Sequelize 4.x which has no `classMethods` anymore. The latest generator and CLI (`feathers-cli@^2.2.0`) already creates models according to Sequelize 4. For more information on how to upgrade your model manually see http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by lfernando-silva** [comment]
Actually I was using v.2.0.5, that was not updated with this changes.  But I also used [sequelize-auto](https://github.com/sequelize/sequelize-auto) to generate the models, as I'm using a legacy database. And in fact, sequelize-auto dependencies has sequelize v3. So, it generates the old-style models.

Thanks for the help!
