### ISSUE TITLE
Update only one parameter in row

### ISSUE THREAD

**Issue by Bubomir** [feathersjs/feathers-sequelize#136]
I have issue with update logic

here in this peace of code in your update function

    Object.keys(instance.toJSON()).forEach(key => {
      if (typeof data[key] === 'undefined') {
          copy[key] = null;
      } else {
         copy[key] = data[key];
      }
    });

This issue occurs when i try to update only a some columns in row.

I have row with 6 columns and I want to update only one specific column in the row.  I send id of row, and data only for one column. That one column update correctly but other columns are null because of if statement show above ...

Would it be possible to change this line 
    `copy[key] = null; `
for something like this:
   `copy[key] = "originalValue"`

**Comment by daffl** [comment]
That's what [.update is supposed to do](https://docs.feathersjs.com/api/services.html#updateid-data-params):

> `update(id, data, params) -> Promise` - replaces the resource identified by id with data

What you want to do is what [.patch is for](https://docs.feathersjs.com/api/services.html#patchid-data-params):

> `patch(id, data, params) -> Promise` - merges the existing data of the resource identified by id with the new data

**Comment by Bubomir** [comment]
ok my fault, great and thank you so much
