### ISSUE TITLE
Hydrate is not compatible with Sequelize 4.x

### ISSUE THREAD

**Issue by dschnare** [feathersjs/feathers-sequelize#138]
### Steps to reproduce

1. Create app with feathers-cli
2. Add service that connects to a SQLite DB using Sequelize
3. Use the hydrate() hook after any service method

See: http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

The issue resides by checking that the `item` is an instance of `Model.Instance`. This has been deprecated in Sequelize 4.x. It should be expanded to support testing item like: `item instanceof Model` for Sequelize 4.x only.

### Expected behavior
No error should be thrown and the `instanceof` test should look at both the `Model.Instance` (if it exists so we can support Sequelize < 4.x) and `Model` so we can support Sequelize 4.x.

### Actual behavior
Error is thrown saying that the right hand side of the `instanceof` operator is not an object.

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@latest

**NodeJS version**:
6.9.1

**Operating System**:
OSX

**Comment by daffl** [comment]
Related #139 and #123

**Comment by daffl** [comment]
Will be closed via https://github.com/feathersjs/feathers-sequelize/pull/139
