### ISSUE TITLE
Is there any full example about database relationship?

### ISSUE THREAD

**Issue by kieusonlam** [feathersjs/feathers-sequelize#141]
I want to find an example about database relationship.

I did make a repo about a blog api for practice - Currently It have Post and Tag with Many to Many relationship. 
https://github.com/kieusonlam/blogapi
follow this tutorial
https://www.youtube.com/watch?v=TUEhRlKxrOQ

I can create Post and Tag with relation. But how about update relation like I have a post with 3 tag, I want to remove one tag from post or so.

From
```
{
  "title": "First Post",
  "tags": [
    { "name": "First Tag" },
    { "name": "Second Tag" },
    { "name": "Third Tag" }
  ]
}
```
to 
```
{
  "title": "First Post",
  "tags": [
    { "name": "First Tag" },
    { "name": "Third Tag" }
  ]
}
```
What did you guys do in real world application?

**Comment by DesignByOnyx** [comment]
This is not really the place to ask questions - please use the FeathersJS Slack channel or StackOverflow. This is also more of a sequelize question than a feathers related one. Once you understand how to accomplish this in sequelize, you can then follow [the guides on sequelize associations with feathers](https://docs.feathersjs.com/api/databases/sequelize.html#associations-and-relations). If you have any further questions, please feel free to reach out in Slack ([join here](http://slack.feathersjs.com/)).

**Comment by kieusonlam** [comment]
Thanks you. I see `question` and `help wanted` in labels. Then I though I can post question here. Sorry for bordering.
