### ISSUE TITLE
All service methods should take into account the query parameter

### ISSUE THREAD

**Issue by jawadst** [feathersjs/feathers-sequelize#143]
### Steps to reproduce

Do a `PUT /service/:entityId?query=...`. The `query` parameter is ignored and is not used to filter (where clause) the entities updated as the service update uses `findById`. PATCH works well.

The SQL that gets generated from the update service when retrieving the existing entity (https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L191) is `SELECT * FROM entities WHERE id ='entityId'` instead of `SELECT * FORM entities WHERE id ='entityId' AND query='...'`.

### Expected behavior

Entities should be filtered with the query-string parameters before being updated.
The actual SQL query should be `SELECT * FORM entities WHERE id ='entityId' AND query='...'`

### Actual behavior

Entities are not filtered.

### System configuration

The reason this is needed is to allow updating nested services/entities which is helpful for managing many-to-many relationships.

**Example**
Two models User and Project with a many-to-many relationship (belongsToMany).
A User service is mounted on `/users/:userId` and a Project service is mounted on `/users/:userId/projects/:projectId`.
A before hook automatically transforms the :userId into a query parameter (`hook.params.query['userId']`).

The find/patch methods behave correctly. For instance, `GET /users/u123/projects/p456` creates the SQL query `SELECT * FROM projects WHERE userId='u123' AND projectId='p456'`.

UPDATE does not behave that way as it uses `findById(projectId)` and, hence, makes it impossible to enforce the `userId` constraint. The many-to-many table has the same `projectId` multiple times so it cannot work.

I have not tested the get and remove method yet. I assume that they'd have the same issue as the update method.

**Comment by daffl** [comment]
What you want to accomplish should be doable by changing the `id` to `null` in a hook to [update multiple records](https://docs.feathersjs.com/api/databases/common.html#adapterupdateid-data-params---promise) and setting the query parameters accordingly:

```js
app.service('users/:userId/projects/:projectId').hooks({
  before: {
    patch(context) {
      context.id = null;
      context.query = {
        userId: context.params.userId,
        projectId: context.params.projectId
      }
    }
  }
});
```

Any call that has an id will always use that id to retrieve the record.

**Comment by jawadst** [comment]
@daffl 
It does not seem to work as I am in an `update` request and not a `patch` (the `patch` works well by rewriting the ``hook.params.query` object as it is taken into account by the service).
The documentation explicitly states that `id` cannot be null for update requests with a database adapter (https://docs.feathersjs.com/api/databases/common.html#adapterupdateid-data-params---promise). I get a `No record found for id 'null'` when I try your solution.

Any reason why we can't switch the `update` method to use the `_getOrFind` method, for instance, instead of `findById`? I am happy to work on a PR for that if that sounds like a viable option.
Another option could be to rewrite/redirect my `update` request to a `patch` request but I haven't seen anything about that in the docs.

**Comment by daffl** [comment]
What is the reason to use `update` at all? An `update` to `patch` redirect hook can be done pretty easily by setting `hook.result`:

```js
app.service('myservice').before({
  update(hook) {
    return hook.service.patch(hook.id, hook.data, hook.params)
      .then(result => {
        hook.result = result;
        return hook
      });
  }
});
```

**Comment by jawadst** [comment]
@daffl
The main reason is consistency, to offer all standard REST methods on all my services. `update` makes some operations a little easier like removing fields from an existing object. It's really the same reasons as all other REST APIs offering `update` + `patch` and Feathers supporting it in the first place :)

Redirecting the `update` to `patch` is an ok short-term fix but does not actually implement a real update behavior (obviously) so it'd be great to be able to support the real update use-case for nested services in `feathers-sequelize` which requires the `update` method of the service to support query filtering.

I still want to point out that the fact that `update` has a different behavior than all the other methods (`get`, `find`, `patch` and `remove`) is a little confusing and unexpected as a user of Feathers. Let me know if I can help fix that. Again, I can work on a PR if you are open to that change (or to a different implementation that'd bring the same result).

PS: Thanks a lot for your quick answers, it's pretty impressive to see the level of support you guys are doing on top of your great work on Feathers!

**Comment by daffl** [comment]
It's a service adapter specific implementation, Feathers does not have any restrictions to support this functionality.

I just can't think of many use cases where you would replace an entire set of instance with the exact same data (in fact very early versions of the adapters supported this and it led to a lot more mistakes and questions than it was useful).

**Comment by jawadst** [comment]
All right, I'll close this ticket then as the solution works for me. Thanks!
