### ISSUE TITLE
Patch returns Model instance by default

### ISSUE THREAD

**Issue by Ryanthegiantlion** [feathersjs/feathers-sequelize#146]
Patch does not default to raw. 

https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L153

The result is that a newly created service with default settings has all the methods providing json in the after hooks except for patch.

**Comment by Ryanthegiantlion** [comment]
I have looked a bit more into feathers-sequelize tests and see that it uses feathers-service-tests which has a tests for this stuff. Since the tests are passing it suggests that patch is working as expected. However the behaviour in my own app and the code suggests otherwise. So I will be following up to determine whats happening here and perhaps write some extra tests to see what is going on.

**Comment by daffl** [comment]
Does that mean we shouldn't publish #147? It looks fine to me.

**Comment by daffl** [comment]
Closed via #147 and released as v2.2.1

Looking forward to a separate PR for the tests!
