### ISSUE TITLE
Support $search

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-sequelize#15]
This is a proposed special attribute that allows you to fuzzy match a property. Possibly even multiple properties and/or nested documents.

Suggested syntax:

```js
name: {
  $search: ['alice', 'Alice', 'bo', /$bob/i]
}
```

Following similar syntax to our other special query filters, this would allow you to filter by a singular value, multiple values (treated like an **or**) and/or regular expressions directly.

Internally sequelize has a [few different options](http://docs.sequelizejs.com/en/latest/docs/querying/). The easiest way to support this syntax would be to use `$ilike: { $any: ['alice', 'Alice', 'bo', 'bob']}`. It's a little redundant but I'm not sure if sequelize supports passing a regex.

**Comment by diego-vieira** [comment]
@ekryski just needed that.

Right now I'm using this:
[http://localhost:3030/users?name[$like]=%diego%](http://localhost:3030/users?name[$like]=%diego%)
which would be the same as
`SELECT * FROM user WHERE name LIKE '%diego%'`

by the way `$iLike` is for PG only.

from sequelize docs
```
$like: '%hat',         // LIKE '%hat'
$notLike: '%hat'       // NOT LIKE '%hat'
$iLike: '%hat'         // ILIKE '%hat' (case insensitive) (PG only)
$notILike: '%hat'      // NOT ILIKE '%hat'  (PG only)
```

**Comment by daffl** [comment]
Moved to https://github.com/feathersjs/feathers/issues/334
