### ISSUE TITLE
[Question] Should new tests be using Postgres or SQLite or both?

### ISSUE THREAD

**Issue by Ryanthegiantlion** [feathersjs/feathers-sequelize#154]
I am looking to add more tests and just wondering we should go about that in terms of choosing the underling RDB. Should all the tests perhaps be migrated over to using Postgres rather than SQLite?
Or should we be replicating all the tests so that they against both Postgres and SQLite?

**Comment by daffl** [comment]
For some reason I'm having trouble getting Postgres to run on my machine. I'm thinking what we might want to do is to run against SQLite in development so that it stays easy for people to develop and test features and additionally Postgres and MySQL on Travis CI.

**Comment by daffl** [comment]
This has been closed via #160. Thanks again @Ryanthegiantlion!
