### ISSUE TITLE
Can't override id field when declaring a (MySQL) service

### ISSUE THREAD

**Issue by manelgarcia** [feathersjs/feathers-sequelize#164]
As the docs states, I should be able to change my `id` field name.

<img width="834" alt="screen shot 2017-09-13 at 16 59 05" src="https://user-images.githubusercontent.com/765890/30384608-1391ecb0-98a5-11e7-98e7-fbcb0984c31e.png">

I'm trying without any success to do the following:

```js
app.use('/cities', MySQLservice({ 
    Model: Cities, 
    id: 'id_city'
}));
```

That has no effect, sequelize is still querying by `id` instead of `id_city`. Any help?

Thanks in advance!

**Comment by daffl** [comment]
That seems odd because it is definitely being tested successfully in https://github.com/feathersjs/feathers-sequelize/blob/master/test/index.test.js#L79 and https://github.com/feathersjs/feathers-sequelize/blob/master/test/index.test.js#L146.

How does the model look like?

**Comment by manelgarcia** [comment]
Ok, my fault, I do have to specify it on my model declaration. (sequelize newbie here)
