### ISSUE TITLE
When i need force sync?

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-sequelize#21]
I can not understand how works `sync` method. 

I have read the documentation about it. But I do not understand anything. When I have to do the synchronization? Each time when i restart my application it will be deleted all the data from database.

Or should I synchronize only the first time when i run the application and the database table has not yet been created?

But what if the model schema changes? Do i have to synchronize again?

Maybe anyone can share a link to a tutorial and examples?

**Comment by ekryski** [comment]
You don't need force sync. That was actually a bug in the generator. You should **not** have it in your code. If you see it in the docs please tell me where or do a PR and I will remove it.

**Comment by kulakowka** [comment]
I have not seen this in the documentation. It seems that I generated application using the old generator.

**Comment by kulakowka** [comment]
The latest version of generator adds this code in every model:

```javascript
user.sync();
```

Why we do this for each model instead sequelize instance?
```javascript
sequelize.sync()
```

**Comment by ekryski** [comment]
@kulakowka I didn't know you could do that. Looks like you can do either one. The choice is yours... :smile:

**Comment by kulakowka** [comment]
Yes thank you. I've already figured out.
