### ISSUE TITLE
Private method _get() not processing parameters

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-sequelize#22]
In method `.get()` it is [possible to pass parameters](https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L79) to the query.

```javascript
get(id, params) {
  return this._get(id, params);
}
```

For example, so:

```javascript
app.service('api/v1/users').get('kulakowka', {
  query: {
    $select: {'username': 1}
  }
})
```

But it **does not work**!

I found the cause. Private method `_get()` [only takes one parameter](https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L58) `id`:

```javascript
_get(id) {
  return this.Model.findById(id).then(instance => {
    if(!instance) {
      throw new errors.NotFound(`No record found for id '${id}'`);
    }

    return instance;
  })
  .catch(utils.errorHandler);
}
```

But it must take two parameters `id` and `params`.

**Comment by daffl** [comment]
What would params do? It doesn't look like [Model.findById](http://docs.sequelizejs.com/en/latest/api/model/#findbyidid-options-promiseinstance) takes options like that.

**Comment by ekryski** [comment]
@daffl I think we used to use `params` for some of the special params like `$select` specifically. However, you can easily do that with hooks too so we probably should just remove the params option from `get`.

**Comment by daffl** [comment]
Well what @kulakowka is saying that it *is* removed in `_get` but mainly because the model call inside does not use it. We could change it to a `find` adds the id and  takes those params and returns only one item.

**Comment by ekryski** [comment]
@daffl I don't think we should do that. it's over complicating things. Unless we have a case where you really need to pass params to a get, it should just take an `id` and we should remove the `params attribute on these lines: https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L79-L80

**Comment by kulakowka** [comment]
I use it for populate `creator` when i get `tutorial`.

```javascript
app.service('/api/v1/tutorials').after({
  get (hook) {
      const creator = hook.result.creator
      const userService = hook.app.service('api/v1/users')

      return userService.get(creator, {
        query: {
          $select: {'username': 1}
        }
      }).then((user) => {
        let result = hook.result.toJSON()
        result.creator = user
        hook.result = result
        return hook
      })
    }
})
```

I think that we should be able to specify parameters for the .get () method. for example in order to be able to specify which fields should be returned from the database.

**Comment by daffl** [comment]
I agree. We just need to make sure that this works the same for all database adapters. Basically the only relevant field would be `$select` right?

**Comment by kulakowka** [comment]
@daffl yes. Other `params` do not have sense for `get()` method. Now the functionality is very limited. We can get the record by id and that's all. And what to do if you want to get the record where username === 'user1' OR 'user2'? 

I have a situation where I need to get the record for two keys. Look this for example:
```javascript
Project.findOne({platform: 'npm', name: 'feathers'})
```

Maybe you can redesign the interface for method `.get()`? I would like to be able to get a single record with some conditions, not only ID. 

For example so:

```javascript
app.service('projects').get({ platform: 'npm', name: 'feathers' })

app.service('todos').get({ id: 123 })

app.service('todos').get(123)
```

**Comment by kulakowka** [comment]
Hmmm... maybe we can make it so:
When `id` param is number - we can use `getById()`.
But when `id` param is object - we can use `findOne()`.

**Comment by ekryski** [comment]
@kulakowka in your case you could easily do a `find` with a `$limit` of 1. I think we're over thinking it here. Looking at mongoose (which is where this originated I think) [we are using it for `$populate`](https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L94). We're not even using it for `$select`.

I think `.get` should support params but only for the sake of `$populate` and `$select` along with an `id`. Otherwise you should be using `.find()`.

**Comment by mrpatiwi** [comment]
I'm not able to use `sequelize.include` from http://docs.feathersjs.com/help/faq.html#the-orm-way

**Comment by mrpatiwi** [comment]
It's easy to fix: https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L58-L59

```js
_get(id, params) {
    return this.Model.findById(id, params.sequelize).then(instance => { ...
```

**Comment by daffl** [comment]
I published a fix for @mrpatiwi's issue. The other issue discussed can now be solved by adding a `before` hook for `get`:

```
app.service('myservice').before({
  get(hook) {
    if(typeof hook.id === 'object') {
      return this.find(hook.id).then(result => {
        const data = result.data || result;

        hook.result = data[0];
        return hook;
      });
    }
  }
});
```
