### ISSUE TITLE
Exporting utils.js

### ISSUE THREAD

**Issue by shadowRR** [feathersjs/feathers-sequelize#58]
Hey guys,

Would be nice if we could access the utils.js file, to use it when extending some of the methods instead of duplicating it. Or maybe it's already possible in another way than going to look for it through the path in node_modules ?

Thanks

**Comment by daffl** [comment]
Couldn't you just `require('feathers-sequelize/src/utils')`? Personally I don't think there is anything in there that should be needed externally on a regular basis so I'm not sure it needs to be exposed explicitly.

**Comment by shadowRR** [comment]
I tried it this way, but it's not working, i get this error : `Error: Cannot find module 'feathers-sequelize/src/utils'` (and i can load feathers-sequelize just fine).

**Comment by daffl** [comment]
Oh yes, it's `feathers-sequelize/lib/utils`

**Comment by shadowRR** [comment]
Yes, perfect. Thanks a lot.
