### ISSUE TITLE
Make params optional

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-sequelize#59]
Some of the methods e.g. `get` require `params` be given (by using `params.sequelize`). This is fine if dealing with an incoming request or via `app.service` (I believe) but if using the service directly without going through `app` it'll throw `TypeError: Cannot read property 'sequelize' of undefined`

**Comment by daffl** [comment]
All Feathers service methods run through the [normalizer mixin](https://github.com/feathersjs/feathers/blob/master/src/mixins/normalizer.js) which should set `params` to an empty object if it doesn't exist.

You do have to make sure to get the service via `app.service('servicename')`instead of using the service instance directly.

**Comment by bedeoverend** [comment]
@daffl is that expected behavior? I noticed quite a few other methods in other feathers hooks do a check for params (e.g. `params && params.foo`). I would expect the ability for it to still work using the service instance directly. 

If this isn't expected behavior, or a concern for this plugin, then happy to close, otherwise also happy to do a PR that runs the checks.

**Comment by daffl** [comment]
You shouldn't use the service instance directly. You won't get hooks or real-time events or anything else that Feathers adds (see [here](http://docs.feathersjs.com/services/readme.html#retrieving-services)).

The hook checks are probably a relic from pre-normalization times (I think that was < 1.3).

**Comment by bedeoverend** [comment]
@daffl Ok, thanks for the information. Happy to close this

**Comment by daffl** [comment]
Thank you for bringing it up. We'll make sure to mention it in more spots in the documentation to make sure it is well known.

**Comment by bedeoverend** [comment]
@daffl No worries, thanks for the quick responses. My interpretation was that it was best practice to get it via `app.service`, rather than a necessity. But having said that, and looking back over the docs, the interface of the methods does indicate `params` as a guaranteed parameter, rather than optional like the callback param: `get(id, params[, callback])`. As you say though, be great if there is more mention in the docs :)
