### ISSUE TITLE
Expose Sequelize lib

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-sequelize#6]
So that end users don't need to require it separately we should just expose the underlying sequelize lib. Just in case people need access to it.

**Comment by daffl** [comment]
I don't think this is necessary (or even possible). You only have to supply the initialized model. The plugin itself doesn't directly depend on Sequelize at all.

**Comment by ekryski** [comment]
Right. Sequelize gets initialized outside of the adapter.
