### ISSUE TITLE
Cannot call remove service method when id field name is custom

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-sequelize#60]
I'm having some issues with the `remove` service method.

I've specified a custom id in my model, e.g.,

```js
  app.use('/tags', service({
    id: 'uuid',
    Model: tags
  }));
```

But when I call the `remove` method, this is the SQL that runs:

```
Executing (default): DELETE FROM `tags` WHERE `id` = '9e098ec7-fc13-4478-ab22-68bd4c416637'
```

And the API returns error message:

```
ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
```

The line looks suspect: https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L143

I think the intended value is `this.id`, not just `id`.

**Comment by daffl** [comment]
You are absolutely correct. Can you submit a PR with the change? 
We really need to add custom ids to the service tests.
