### ISSUE TITLE
ES6/Babel

### ISSUE THREAD

**Issue by hdon** [feathersjs/feathers-sequelize#68]
Hi,

I cloned, npm installed, and node examples/app using node 4.5.0 LTS. I got a syntax error on "import" keyword. Ok, so this is using ES6 I guess. The README doesn't mention this, though.

**Comment by daffl** [comment]
You have to `npm run compile` or `npm test` to get the Babel transpiled code. The version published on NPM already provides the transpiled code which works on all Node versions.

**Comment by daffl** [comment]
The process to work with cloned repositories from GitHub has now been documented in the main repo [contributing.md](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md).
