### ISSUE TITLE
Solved: How to add relationship

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/feathers-sequelize#80]
After several days i don't know what to do anymore. My use case is simple:

> After a user is created let's add a default item to his inventar (MxN relationship)

According to the [sequelize docs](http://docs.sequelizejs.com/en/v3/docs/associations/#associating-objects) we just call the appropiate prototype function.

Let's say we have an after hook as following:

```
return function(hook) {
    if(hook.result){                                        //If user creation was successful
      hook.app.service('items').get(1).then(item=> {        //Find default item ...
        hook.result.addInventory(item);                     //and add it to the user
      });
    }
  };
```

FYI, this is the model relation definition(vice versa for items):
```
user.associate = function(models) {
    user.belongsToMany(models.items, { as:'Inventories', through: 'inventories'});
  };
```

**Comment by eikaramba** [comment]
I got it working finally! I updated my code above. Don't know why it wasn't working like that from the beginning(must have made some silly error).

**Comment by daffl** [comment]
You have to `return` the promise, otherwise the hook won't wait for it to finish (which means that if the above code works it is only by accident):

```js
return function(hook) {
  if(hook.result) {
    return hook.app.service('items').get(1).then(item => {
      hook.result.addInventory(item);
    });
  }
};
```

**Comment by eikaramba** [comment]
In this case even `hook.result.addInventory(1)` will work. Sequelize supports it to add a relation just with the ID alone.
