### ISSUE TITLE
Concat and other sequelize functions

### ISSUE THREAD

**Issue by EddyBorja** [feathersjs/feathers-sequelize#81]
Is it possible to use a function like concat in a query?

**Comment by daffl** [comment]
For reference [from this Stackoverflow question](http://stackoverflow.com/questions/41386382/how-to-concat-two-columns-for-search-with-feathers-sequelize/41400168#41400168) you can use a hook to modify `params.query`.

```js
app.service('users').before({
  find(hook) {
    const where = Sequelize.where(Sequelize.fn("concat",
      Sequelize.col("firstname"),
      Sequelize.col("lastname")), {
        like: '%John Do%'
      }
    );

    hook.params.query.where = where;
  }
})
```

**Comment by EddyBorja** [comment]
Will a hook like this be required for every database function?

**Comment by daffl** [comment]
Yep. You can implement a global hook that allows some of that functionality for every service via `app.hooks({})` though.
