### ISSUE TITLE
updated_at column does not get updated at PATCH request

### ISSUE THREAD

**Issue by galioy** [feathersjs/feathers-sequelize#88]
### Steps to reproduce
1. Use Postgres
2. Create a new service with a model with a table
3. Make sure the model has `created_at` and `updated_at` columns and some other column that you can update (patch) afterwards (i.e. `note`)

```
return sequelize.define('test_table', {
note: {
      type: Sequelize.TEXT,
      allowNull: false
    },

updatedAt: {
      field: 'updated_at',
      type: Sequelize.DATE,
      allowNull: false,
      defaultValue: Sequelize.NOW
    },

createdAt: {
      field: 'created_at',
      type: Sequelize.DATE,
      allowNull: false,
      defaultValue: Sequelize.NOW
    }
}, {
    // http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration
    freezeTableName: true,
    timestamps: false
});
```

4. Create a new record in the table
5. Make a `PATCH` request to update the `text` column

### Expected behavior
The `updated_at` column should get updated with the time of the update performed (and thus be different from the `created_at` column value).

_Note_: in fact I replace the `updated_at` and `created_at` with `update_time` and `create_time` by renaming the properties in the model definition and then in the options object I add:
```
    updatedAt: 'updateTime',
    createdAt: 'createTime'
```
bellow the `freezeTableName` and `timestamps` properties.
I've been working with this approach with Sails.js + Sequelize and works fine.

But nevertheless, here I switched to `updatedAt` and `createdAt` just to test from the zero.

### Actual behavior
The `updated_at` column does not get updated.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 
```
    "feathers-sequelize": "^1.4.0",
    "sequelize": "^3.24.3"
```
**NodeJS version**:
`v6.9.4`
**Operating System**:
OS X El Capitan

**Comment by galioy** [comment]
Okay... rookie mistake... or rather the phenomenon of realizing the problem and its solution only when you explain your problem to someone (in this case posting an issue).
The problem was that I had set `timestamps` to `false` in the model definition, thus telling Sequelize to _not_ handle the timestamps.

**Comment by marshallswain** [comment]
Glad you got it figured out!  :)

**Comment by hidnarola** [comment]
I am using sequelize version "^4.37.6". and I want to update "updatedAt" field according to my input not current timestamp. but it's updating as the current timestamp. is there any solution for that.

In my model defination I have put timestamp: false.
In my sequelize migration file I give 
updatedAt: {
          allowNull: false,
          type: Sequelize.DATE,
        }

could you please give me any solutions for this.

**Comment by manoharreddyporeddy** [comment]
Some of the below combinations may help:

  // don't forget to enable timestamps!
  timestamps: true,

  // I don't want createdAt
  createdAt: false,

  // I want updatedAt to actually be called updateTimestamp
  updatedAt: 'updateTimestamp'

source: see https://sequelize.readthedocs.io/en/2.0/docs/models-definition/
