### ISSUE TITLE
$populate does not seem to work

### ISSUE THREAD

**Issue by garrypolley** [feathersjs/feathers-sequelize#89]
### Steps to reproduce
Create a linked relationship between two models

### Expected behavior
When I query a basic endpoint I expect the `$populate` parameter to include my related model.

### Actual behavior
The related model is not included in my results.  The `include` never gets sent to sequelize and therefore the inner join is never made.

**Comment by daffl** [comment]
Does Sequelize support `$populate`? I thought that was a Mongoose thing.

**Comment by garrypolley** [comment]
They support an `include` which does about the same thing.  So if I have `hasMany` relationship, I can add a: 

`.findAll({
   include: 'MyManyModel'
  })
`

And it'll add the nested model via an inner join. I was assuming that a `$populate` would drop the value into `include`.

**Comment by garrypolley** [comment]
For further clarification --> http://docs.sequelizejs.com/en/latest/docs/models-usage/?highlight=include#including-everything

I think it'd be possible to do something like what's below, with maybe a bit more logic to use the proper model name/instance in the `include`. 

```js
return this.Model.findAndCount(q).then(result => {
      return {
        include: filters.$populate, // more logic may be needed to refer to the model by name. 
        total: result.count,
        limit: filters.$limit,
        skip: filters.$skip || 0,
        data: result.rows
      };
    }).catch(utils.errorHandler);
```

**Comment by daffl** [comment]
Yes, you can do that by setting `params.sequelize` in a hook:

```js
app.service('sequelizeService').before({
  find(hook) {
    hook.params.sequelize = {
      include: hook.params.query.$populate
    }
  }
});
```

**Comment by garrypolley** [comment]
Thanks! That works with me doing a `hooks.app.get('models')[hooks.params.query.$populate]`

It'd be nice if it "just worked" out of the box though and not requiring a hook. 

I suppose I could add a "global" hook, but those tend to look a little weird/hacky in implementation if I recall.

**Comment by daffl** [comment]
Not anymore, you can use [app.hooks](https://blog.feathersjs.com/feathers-application-and-error-hooks-7a5982e70024?source=user_profile---------1----------).

**Comment by garrypolley** [comment]
Awesome! That's exactly what I'd be happy with for now. Thanks for the help!

**Comment by L3V147H4N** [comment]
This does not work for me... 
```javascript
this.UsersService.find({
      query: {
        $sort: {
          name: 1
        },
        $populate: [
          {
            model: 'Role', as: 'roles'
          }
        ]
      }
    })
`

throws `self.$expandAttributes is not a function`

**Comment by sarkistlt** [comment]
it won't work because 'Role' is string not a model, I'm using this hook:

```js
function resolveModels(arr, models) {
  const include = [];

  arr.forEach((entity) => {
    if (typeof entity === 'string') {
      include.push(entity);
    } else if (typeof entity === 'object') {
      if (entity.model && typeof models[entity.model] === 'function') {
        entity.model = models[entity.model];
      }
      if (entity.include && Array.isArray(entity.include)) {
        entity.include = resolveModels(entity.include, models);
      }
      include.push(entity);
    }
  });

  return include;
}

export default function sequalizePopulateHook(ctx) {
  if (
    ctx.params.query &&
    ctx.params.query.$populate &&
    Array.isArray(ctx.params.query.$populate)
  ) {
    const { models } = ctx.app.get('sequelize');

    ctx.params.sequelize = ctx.params.sequelize || {};
    ctx.params.sequelize.include = resolveModels(ctx.params.query.$populate, models);
    ctx.params.sequelize.raw = false;

    delete ctx.params.query.$populate;
  }
  return ctx;
}
```

it will resolve model from string in:

```js
$populate: [
  {
    model: 'Role', as: 'roles'
  }
]
```
