### ISSUE TITLE
Can we create nested models in one go?

### ISSUE THREAD

**Issue by achrome** [feathersjs/feathers-sequelize#97]
If I want to create multiple models in one go, can I do so?

For example, I have a `Customer` that has a `Contact` associated with it.

```es6
export default (sequelize, DataTypes) => {
  const Customer = sequelize.define('customer', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true
    }
  }, {
    classMethods: {
      associate() {
        const models = sequelize.models;
        Customer.hasOne(models.contact);
      }
    },
    tableName: 'customers'
  });
  return Customer;
};
```

I run sequelize's associations while importing the models, like so

```es6
Object.keys(db)
    .map(name => db[name])
    .filter(model => model.associate)
    .forEach(model => model.associate());

sequelize.sync();
```

Finally, I have the customer service defined like this

```es6
class CustomerSvc extends DBService {
  constructor() {
    super({
      Model: db.customer
    });
  }

  create(data, params) {
    return super.create(data, Object.assign({}, params, { sequelize: { include: [db.contact] } }));
  }
}

export default function() {
  return this.use('/customers', new CustomerSvc());
}
```

Now, the problem that I am stuck on is creating a contact along with the customer in one go.

For example,

```
POST /api/customers
{
  "contact": {
    "firstName": "Test",
    "lastName": "Test"
  }
}
```

I want this to create the contact if it doesn't exist, and fetch and use a contact if the contact ID is passed. But what feathers is doing is only running the query to create the customer without the contact.

This is what I see in the logs.

```
Executing (default): INSERT INTO "customers" ("id","createdAt","updatedAt") VALUES (DEFAULT,'2017-03-21 14:43:48.195 +00:00','2017-03-21 14:43:40.187 +00:00') RETURNING *;
```

Please advise on the best way to approach this problem.

**Comment by eikaramba** [comment]
currently that does not work with feathers-sequelize. But you can use an after hook to handle this after creating the customer. The actual "findOrCreate" logic you want to have is not there as well. Therefore you either do it yourself via 2 api calls or you write your own service which itself is directly using the sequelize model in its own create method. But tbh i would just first query, then create and with the after hook create the customer.

**Comment by achrome** [comment]
Okay. Well I'm going to hack around a bit on this. Will revert with some code once I manage to do something here.
